inertial_frame_id: world
waypoints:

  -
    point: [40, 20, -32]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [35, 30, -25]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [20, 20, -32]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [20, -20, -35]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [40, -20, -59]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [100, -40, -59]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False

